### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by Spinor16** [datakurre/setup.nix#13]
Hi, I have an issue with the installation, could you help me? The error message shown is

```
Collecting pip<10,>=8 (from pip2nix==0.8.0.dev1)
  Could not find a version that satisfies the requirement pip<10,>=8 (from pip2nix==0.8.0.dev1) (from versions: )
No matching distribution found for pip<10,>=8 (from pip2nix==0.8.0.dev1)
builder for '/nix/store/vs9b5ffi2nc3wdxjd311b05ypw3f2gdg-python3.6-pip2nix-0.8.0.dev1.drv' failed with exit code 1
cannot build derivation '/nix/store/l47xl55hdlc5345l8bbjg64921lww67p-python3-3.6.5-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/l47xl55hdlc5345l8bbjg64921lww67p-python3-3.6.5-env.drv' failed
```
I tried (via pyenv) to install different pip-version, among them 9.0.0. What am I doing wrong?
Thanks in advance!

**Comment by datakurre** [comment]
Could you provide any more information of your nix expression?

My first guess is that you are using nixpkgs master or NixOS 18.09 and setup.nix version for README. I have not updated the versions in README yet, but repo master is compatible with latest nixpkgs.

**Comment by Spinor16** [comment]
Hi, thanks for your reply! Okay yes this is indeed the case (I work on ubuntu and fetched the latest nixpkgs channels). I adjusted the url and sha256 in setup.nix, but have still not been successful though. The setup.nix file looks as follows:


```
{ pkgs ? import <nixpkgs> {}
, pythonPackages ? pkgs.python3Packages
, setup ? import (fetchTarball {
    url = "https://github.com/datakurre/pip2nix/archive/c9e9d575a7093af0cd44697ca91ff01ac83c9565.tar.gz";
    sha256 = "03jdr5hgg7dbg029h455x6lz84xfk3ngji7bwj1wy0b049pq3qkg";
  })
}:

setup {
  inherit pkgs pythonPackages;
  src = ./.;
}
```


After running 
`nix-shell setup.nix -A pip2nix --run "pip2nix generate -r requirements.txt --output=requirements.nix"`
I get the message 
`error: anonymous function at /nix/store/0gq9xi6i7q3xwjzqx5k0p431sdi61qss-source/default.nix:1:1 called with unexpected argument 'src', at /home/dedennler/test_nix_setup/setup.nix:9:1
`
I tried to remove the src and performed some other minor changes, did not work for me. Sorry I am a bit lost, would appreciate the help. Thanks!

**Comment by datakurre** [comment]
@Spinor16 Maybe the url in fetcTarball to use setup.nix -repository instead of pip2nix repository.

```
{ pkgs ? import (fetchTarball {
    url = "https://github.com/NixOS/nixpkgs-channels/archive/29660a208552a1e32f872333d6eb52e13226effa.tar.gz";
    sha256 = "1rv87f7kqrnl16m64h4148c6nnnl3r3m860d0f08dwk1d5f6ffmd";
  }) {}
, setup ? import (fetchTarball {
    url = "https://github.com/datakurre/setup.nix/archive/d991abe23efde4a0bc5de2a0b4672cca0126c151.tar.gz";
    sha256 = "0zglrif1hncs84ia28m03ca324y8aqnjqygzsji7x0bnfn77hpqm";
 })
, pythonPackages ? pkgs.python3Packages
}:
```

Here is an example of my current usage: https://github.com/datakurre/robotkernel/blob/master/setup.nix

To stay sane with hashes I use curl, jq, nix-prefetch-url and GitHub REST API to upgrade them when necessary: https://github.com/datakurre/robotkernel/blob/master/Makefile#L11

**Comment by Spinor16** [comment]
Thanks a lot, with your example I got the installation running as supposed.
