### ISSUE TITLE
Issue with pip2nix

### ISSUE THREAD

**Issue by leenaars** [datakurre/setup.nix#15]
Thank you for this nice solution, which will be very useful for many people I believe. For now I run into a blocking issue with generating the requirements.nix. Following the README:

nix-shell shell.nix -A pip2nix --run "pip2nix generate -r requirements.txt --output=requirements.nix"
error: attribute 'majorVersion' missing, at /nix/store/7ahg614q6g8qnvbw5vp3s4cpafb5ksla-source/default.nix:173:45
(use '--show-trace' to show detailed location information)

Note: I'm attempting to get a Python2 Django application up and running.

If I directly use pip2nix, I run into the new version of pip in nixpkgs not working with pip2nix...

**Comment by leenaars** [comment]
# Define commmon targets
in {

  # Define known good version of pip2nix environment
  pip2nix = (pythonPackages.python.withPackages (ps: [
    (getAttr
      ("python" + replaceStrings ["."] [""] pythonPackages.python**.majorVersion**)
      (import (pkgs.fetchFromGitHub {
        owner = "datakurre";
        repo = "pip2nix";
        rev = "0eff2793fb760b5dd3a7c0b9145d11840222fd0e";
        sha256 = "0cm7pkg1sz0vrk9hihwxbk0nl6qh0yd8h4dmsp669m4pzkpff3zd";
      } + "/release.nix") { inherit pkgs; }).pip2nix
    )
  ])).env;

  # Define convenient alias for the final set of packages
  pythonPackages = packages;

**Comment by datakurre** [comment]
@leenaars Could you please try again with the latest master and re-open this issue if you continue to have errors.
