### ISSUE TITLE
I want to use Python packages from nixpkgs and from PyPI in a Juypter notebook. Is setup.nix right for me?

### ISSUE THREAD

**Issue by das-g** [datakurre/setup.nix#4]
I'm using NixOS and would like to launch a Jupyter notebook and have `shapely` and `fiona` available in that.

`nixpkgs` already contains `python36.packages.jupyter` and `python36.packages.shapely`, but not (yet) fiona. `jupyter`, `shapely` and `fiona` are available on PyPI, but I'd like to use the `nixpkgs` versions if possible, so that I don't have to figure out their non-Python dependencies.

`fiona` has only `gdal` as non-Python dependency, as far as I can tell.

Thus, I think I should create a nix environment with `jupyter` and `shapely` from `nixpkgs` and with `fiona` from PyPI (but built against `gdal` from `nixpkgs`).

Can I do that with `setup.nix` and is it the right tool for that kind of tasks?

If so, how would I do that? (I assume `buildInputs` and `propagatedBuildInputs` are for _direct_ non-Python dependencies, not for non-Python dependencies _of my dependencies_.)

**Comment by datakurre** [comment]
I’ll provide you an example soonish. setup.nix may help a bit, jupyter needs some extra configuration... (and I haven’t adapted my nix jupyter config yet for NixOS jupyter module).

**Comment by datakurre** [comment]
@das-g I made an example for you

https://github.com/datakurre/setup.nix/tree/master/examples/jupyter

in that folder
```
nix-shell --run "jupyter notebook"
```
should launch a Jupyter notebook withhttps://gist.github.com/datakurre/681bd6ca3e7baaff96104e90e84702df Python 3.6 kernel with your packages on it. It's a standalone example and works also outside the repository. Requires Nix 2.0 (default on nixos-unstable).

Adding regular Python packages without any binary dependencies should be as easy as adding them into ``./kernel/requirements.txt`` and running ``make`` in ``./kernel``. If package doesn't build, but it available on Nixpkgs, follow examples in ``./kernel/Makefile`` and ``./kernel/setup.nix`` to re-use packaging instructions from Nixpkgs but versions from PyPI.

That Jupyter notebook configuration is static with only some runtime data stored into ``.jupyter`` and ``.ipynb_checkpoints`` directories under current working directory. The configuration uses separate Python environments for the notebook and the kernel (notebook is built from Nixpkgs packages, but kernel is environment is built using setup.nix). It's possible to add multiple separate kernels into that configuration by just following the example.

If you need to add Jupyter extensions onto the notebook itself, it's more involved. Here's a messy example, where I have some nbextensions installed and configured: https://gist.github.com/datakurre/681bd6ca3e7baaff96104e90e84702df

**Comment by das-g** [comment]
Wow, thanks!

**Comment by das-g** [comment]
Works as advertised. :smiley:

:thinking:  What are all those nix expressions doing and why are they needed? (E.g., why is a custom IPython/Jupyter kernel needed in this case?)

It seems that when I only need Python packages already available as NixOS derivations in `nixpkgs`, something like
```bash
nix-shell -p 'python3.withPackages(p:[p.jupyter p.folium p.gdal])' --run 'jupyter notebook'
```
(without any custom `*.nix` files) suffices. (So it seems that the default Jupyter kernel is able to pick up libraries installed next to it.)

On the other hand, it seems that when using IPython (or even just `python`), I can freely combine `nix`-installed and `pip`-installed libraries:
```bash
$> nix-shell -p 'python3.withPackages(p:[p.ipython p.gdal])'  # note: no folium yet
nix-shell $> python -m venv --system-site-packages myvenv
nix-shell $> . myvenv/bin/activate
(myvenv) nix-shell $> pip install folium
(myvenv) nix-shell $> ipython
In [1]: import folium
In [2]: import gdal
```

Is it the combination of all three, Jupyter + `nix`-installed Python packages + `pip`-installed Python packages, that requires us to jump through so many hoops?

**Comment by datakurre** [comment]
Raphael Das Gupta wrote:
> nix-shell -p'python3.withPackages(p:[p.jupyter p.folium p.gdal])'  --run'jupyter notebook'
>
> (without any custom |*.nix| files) suffices. (So it seems that the
> default Jupyter kernel is able to pick up libraries installed next to it.)

That's correct. Jupyter has its default python environment as its 
default kernel available. And if that's enough, and all packages are 
already available, it's enough :)

I often need multiple kernels, or non-Python kernels, or different 
package version that are currently available on NixOS. That's only when 
something more complex is needed.

**Comment by cdyson37** [comment]
Apologies if this is a little off topic, but @das-g's example doesn't work for me:
```
$ nix-shell -p 'python3.withPackages (p: [p.ipython p.gdal])'
$ python -m venv --system-site-packages myvenv

# Import from the nix-shell is fine
$ python -c "import gdal"

# Make and activate venv
$ python -m venv --system-site-packages myvenv
$ . myvenv/bin/activate

# Install something with pip if you like, then...
$ python -c "import gdal"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'gdal'
```

What *does* work is using the nix-shell version of ipython (not the one in the venv) but with the venv activated. That's not much good for my use case though 😞 

Do you think this is something fixable in nixpkgs?

**Comment by datakurre** [comment]
@cdyson37 Have you tried with creating the virtualenv using virtualenv-package from nixpkgs?

**Comment by cdyson37** [comment]
Thanks for the tip! It appears to work (at least for modules that are easy to build) although it produces a lot of warnings about not being able to build a wheel:
```
$ nix-shell -p 'python3.withPackages (p: [p.ipython p.gdal p.virtualenv])'
$ python -m virtualenv --system-site-packages myvenv

# Works
$ ./myvenv/bin/python -c "import gdal"

$ ./myvenv/bin/pip install hjson
...
  creating build/bdist.linux-x86_64/wheel/hjson-3.0.1.dist-info/WHEEL
  creating '/run/user/1000/pip-wheel-jlc45_gt/hjson-3.0.1-cp37-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/run/user/1000/pip-install-u_6rokjs/hjson/setup.py", line 78, in <module>
      run_setup()
    File "/run/user/1000/pip-install-u_6rokjs/hjson/setup.py", line 76, in run_setup
      **kw)
    File "/home/nix/tmp/myvenv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/nix/store/65brrgqndksqgi5698kiy90nm3gq3mz0-python3-3.7.3-env/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/nix/store/65brrgqndksqgi5698kiy90nm3gq3mz0-python3-3.7.3-env/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/nix/store/65brrgqndksqgi5698kiy90nm3gq3mz0-python3-3.7.3-env/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/nix/tmp/myvenv/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 254, in run
      wf.write_files(archive_root)
    File "/home/nix/tmp/myvenv/lib/python3.7/site-packages/wheel/wheelfile.py", line 124, in write_files
      self.write(path, arcname)
    File "/home/nix/tmp/myvenv/lib/python3.7/site-packages/wheel/wheelfile.py", line 135, in write
      zinfo = ZipInfo(arcname or filename, date_time=get_zipinfo_datetime(st.st_mtime))
    File "/nix/store/65brrgqndksqgi5698kiy90nm3gq3mz0-python3-3.7.3-env/lib/python3.7/zipfile.py", line 357, in __init__
      raise ValueError('ZIP does not support timestamps before 1980')
  ValueError: ZIP does not support timestamps before 1980
  ----------------------------------------
  ERROR: Failed building wheel for hjson
  Running setup.py clean for hjson
Failed to build hjson
Installing collected packages: hjson
  Running setup.py install for hjson ... done
Successfully installed hjson-3.0.1
```

(I'll have a go at using setup.nix instead..!)

**Comment by datakurre** [comment]
I recall that warning cannot (or has side-effects to) be fixed in nixpkgs, but must be fixed per use. I seem to have fixed it once by setting source date for all nixed python executables https://github.com/datakurre/nix-files/blob/3c4ebe21b6465048fe22dada034fdaf3160f52d2/overlays/custom/zest-releaser/default.nix#L40

But if everything works even with the error then that’s probably good enough for you :)
